{"name": "тест создания дубликата пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'Email, passw...quired fields' == 'User already exists'\n  \n  - User already exists\n  + Email, password and name are required fields", "trace": "self = <tests.test_create_user.TestApiCreateUser object at 0x000002239269A3D0>, user_data = <Response [200]>\n\n    @allure.title('тест создания дубликата пользователя')\n    def test_create_duplicate_user_error(self, user_data):\n        payload = user_data\n        response = requests.post(EndpointsUrl.CREATE_USER, data=payload)\n        assert response.status_code == 403\n>       assert response.json()['message'] == ErrorMessage.EXIST_USER\nE       AssertionError: assert 'Email, passw...quired fields' == 'User already exists'\nE         \nE         - User already exists\nE         + Email, password and name are required fields\n\ntests\\test_create_user.py:19: AssertionError"}, "start": 1709681154624, "stop": 1709681154782, "uuid": "dfb54423-73a1-4cf3-98e9-5eb603de3ce4", "historyId": "9fcf997048f84fc59547e32e0c492846", "testCaseId": "9fcf997048f84fc59547e32e0c492846", "fullName": "tests.test_create_user.TestApiCreateUser#test_create_duplicate_user_error", "labels": [{"name": "feature", "value": "Проверяем создание пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestApiCreateUser"}, {"name": "host", "value": "DESKTOP-AQ71LTK"}, {"name": "thread", "value": "10368-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}