{"name": "тест создания дубликата пользователя", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "self = <allure_commons._allure.fixture object at 0x000001E3D3DCF100>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\nvenv\\lib\\site-packages\\allure_commons\\_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @pytest.fixture\n    def user_data():\n        payload = helpers.payload\n        response = requests.post(EndpointsUrl.CREATE_USER, data=payload)\n    \n        yield payload\n>       token = response.json()['accessToken']\nE       KeyError: 'accessToken'\n\nconftest.py:22: KeyError"}, "start": 1709681539973, "stop": 1709681540140, "uuid": "44b26435-153a-4eea-bbc1-7d453f017a21", "historyId": "9fcf997048f84fc59547e32e0c492846", "testCaseId": "9fcf997048f84fc59547e32e0c492846", "fullName": "tests.test_create_user.TestApiCreateUser#test_create_duplicate_user_error", "labels": [{"name": "feature", "value": "Проверяем создание пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestApiCreateUser"}, {"name": "host", "value": "DESKTOP-AQ71LTK"}, {"name": "thread", "value": "10156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}