{"name": "Получение заказа авторизованного пользователя", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "@pytest.fixture\n    def user_token():\n        payload = helpers.payload\n        response = requests.post(EndpointsUrl.CREATE_USER, data=payload)\n>       token = response.json()['accessToken']\nE       KeyError: 'accessToken'\n\nconftest.py:31: KeyError"}, "start": 1709681186609, "stop": 1709681186609, "uuid": "b1befdfb-eca3-49b2-bcae-f2f0b370fc04", "historyId": "baa7c46917b31cc9dd66d3f5061b882c", "testCaseId": "baa7c46917b31cc9dd66d3f5061b882c", "fullName": "tests.test_get_order.TestApiGetUserOrders#test_auth_user_get_order_successful", "labels": [{"name": "feature", "value": "Проверяем получение заказа пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestApiGetUserOrders"}, {"name": "host", "value": "DESKTOP-AQ71LTK"}, {"name": "thread", "value": "13036-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}